### PR TITLE
NVG Battery

### PR DESCRIPTION
**Pull request by Mocha-Not-Latte**
## About The Pull Request

Makes the Tactical Ballistic Helmet NVG consistent with the other NVG options. 
port of - https://github.com/discordia-space/CEV-Eris/pull/6686 

## Why It's Good For The Game

We like consistency don't we?

## Changelog
```changelog
tweak: Makes the Tactical Ballistic Helmet NVG now take batteries.
```

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
CI failing is due to some issue with `reader.dm`, which is not caused by this PR. For any commits **before** this comment, CI failure shouldn't block this PR.

**Review by Jamini — APPROVED** [review]
As per shadow. This looks fine.

**Review by Jamini — CHANGES_REQUESTED** [review]
However as the path has changed, anything that uses the /obj/item/clothing/glasses/bullet_proof_ironhammer path needs to be updated to /obj/item/clothing/glasses/powered/bullet_proof_ironhammer path

**Review by Jamini — APPROVED** [review]
I am the dumb. The powered glasses are only referenced here. Should be good.

**Pull request merged**
