### PR TITLE
erisportserisportserisports

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

eris ports

## Why It's Good For The Game

https://github.com/discordia-space/CEV-Eris/pull/6070
https://github.com/discordia-space/CEV-Eris/pull/5923
https://github.com/discordia-space/CEV-Eris/pull/5997
https://github.com/discordia-space/CEV-Eris/pull/5977
https://github.com/discordia-space/CEV-Eris/pull/5745

## Changelog
```changelog
add: new beaker/chem sprites, new admin ticket system, now you have two kidneys, fbp's spawning w/ organic organs sohuld be fixed
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
**can't** get the character customization working. everything else in here works perfect. sorry, yall.

**Comment by bearrrrrrrr** [comment]
to be noted, someone will want to do a check-over this and make sure i did'nt keep in code that kept the thing of sending something via webhook >.> swear i commented it out, but still

**Review by Jamini — APPROVED** [review]
Everything looks good. I'm going to trust that Bear tested what they could. I'll patch up any loose ends. Approved.

**Comment by bearrrrrrrr** [comment]
Yeah, couldn't test the ticket system since that'd...need more than one person, lol. sorry.

**Pull request merged**
