### PR TITLE
Bumps up noble starting funds from 5x to 10x

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Jams said he wanted it at 10x for a reason (see below), so here we go. I don't particularly care if this is merged or not.

## Why It's Good For The Game

Image from the preserved fruit themselves:
image

## Changelog
```changelog
tweak: Nobles now get 10x the starting amount, up from 5x.
```

(just... ignore the changes to the comments)

### CODE REVIEW

**Review by Jamini — APPROVED** [review]
Just Var changes, I'll leave it to Tori if he wants to Emojicracy or not.

**Comment by Michiyamenotehifunana** [comment]
Maybe we could see how this goes first, _then_ emojicracy to get people's thoughts.

**Comment by Jamini** [comment]
Works fine. I highly doubt anyone is really going to notice.

**Comment by bearrrrrrrr** [comment]
don't fucking know about this one chief lmao. this seems like a _rediculously_ bad idea.

**Comment by RadiantFlash7** [comment]
NGL, I'm kinda with bear on this. 10x increase? Like... If you make 3K, you get 30K. Thats... a lot. Enough to break the economy and allow people to clear out all of cargos stock/make money an insignifigance.

**Comment by bearrrrrrrr** [comment]
yeaah. like, i'd be fine with a x2 or even a x3 but x10 is just...idk. too much.

**Comment by Jamini** [comment]
We'll emojicracy this at some point. x5 is fine.

I don't think a lot of you realize just how much money "Rich" people have compared to ordinary shlubs though.

**Pull request closed without merging**
