### PR TITLE
Equal Opportunity Sports Vestiments

### PR DESCRIPTION
**Pull request by cebutris**
## About The Pull Request

Male Mekhane Sports vestments previously did not show midriff. They do now. Shameless fetish content, sue me.

(I just copied over the female version to replace the old male version, and made it very slightly wider to fit with the rest of the male suit sprites)

## Why It's Good For The Game

tummy.....

## Changelog
```changelog
imageadd: The male and female church sports vestments are now more consistent with each other
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
can we have a pic of the new sprite on a person?

**Comment by cebutris** [comment]
image
male on right, female on left. It's just two pixels of difference on both the front and back facing (not pictured, but it's v similar)

**Comment by cebutris** [comment]
Changed it slightly. Spot the difference 
image

**Comment by ShadzFen** [comment]
Gonna have to change it to be modular. Directly overwriting old sprites causes conflicts within the code.

**Comment by cebutris** [comment]
Made it modular and changed the sprites some more! A lot more, actually. 
image

**Review by ShadzFen — APPROVED** [review]
Looks good. New modular folders and files for uniform clothing. All good

**Pull request merged**
