### PR TITLE
Advanced Surgery and Multy tool

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Adds quite a few things - 
New advanced multy tool, even has a nice sleek black sprite!
Uses a medium cell (so we can take power tool upgrades!)
Has 4 upgrade slots
Pluse rating of 60.
Requires gold and silver to make, or luck!
image

Advanced Surgery tools
One of each normal type of surgery tool now has an advanced version.

Advanced surgery disk!
Has all the new advanced surgery tools, + laser scaple rather then normal one

## Why It's Good For The Game

Its on the list of todos and advanced tools to reward players for finding them is always nice.

image

Tho, it isnt built in silenced.

## Changelog
```changelog
add: New advanced multy tool has been added.
add: Advanced surgery tools can be found only at this time.
```

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
image

**Comment by Jamini** [comment]
That checklist is quite old. The technological parts have since been dramatically debuffed. For now let's keep them giving perks.

I believe we wanted the advanced surgical tools to be researchable. Not on a disk?

You should not need to give it a bonus 20% workspeed. The higher pulse rating should do that for you.

Can you post images of all the items so we can have Toriate look at the sprites?

**Comment by Trilbyspaceclone** [comment]
> I believe we wanted the advanced surgical tools to be researchable. Not on a disk?

Its coded so if you want to make a new node for the surgery stuff you can do it with easy. Issue is that that im not a 100% sure what kinda rnd balance we wanted with them so left it as a disk for someone whoms a bit more understanding of the balance can tweak at.

> Can you post images of all the items so we can have Toriate look at the sprites?

Icon diff should show all the icons I put in.
Only new icon is the advanced multy tool I posted
Advanced surgery tools are same icon as base ones.

**Comment by Jamini** [comment]
> > I believe we wanted the advanced surgical tools to be researchable. Not on a disk?
> 
> Its coded so if you want to make a new node for the surgery stuff you can do it with easy. Issue is that that im not a 100% sure what kinda rnd balance we wanted with them so left it as a disk for someone whoms a bit more understanding of the balance can tweak at.
> 
> > Can you post images of all the items so we can have Toriate look at the sprites?
> 
> Icon diff should show all the icons I put in.
> Only new icon is the advanced multy tool I posted
> Advanced surgery tools are same icon as base ones.

The issue with putting them on a disk is that ironically that makes these more accessible rather than less. Advanced medical tools should really be the realm of research and medical. Adding them to an existing node is fine.

You may want to collaborate with Toriate to get unique icons for the advanced tools. Since being able to tell tools apart visually is important.

**Comment by Trilbyspaceclone** [comment]
> 
> The issue with putting them on a disk is that ironically that makes these more accessible rather than less. Advanced medical tools should really be the realm of research and medical. Adding them to an existing node is fine.
> 
> You may want to collaborate with Toriate to get unique icons for the advanced tools. Since being able to tell tools apart visually is important.



Want me to just have them all commit out for ya to work?

**Comment by Jamini** [comment]
That is fine. IF you could also blacklist the items I'd appreciate it. Like most high-end prototypes we don't want this stuff floating in maint generally.

**Comment by Trilbyspaceclone** [comment]
Sure thing give me a moment

**Comment by ShadzFen** [comment]
The section 3 maintenance medbay has two surgery rooms that can already spawn existing advanced surgery tools. Might be an idea to add these new ones to that spawn pool too.

**Comment by Trilbyspaceclone** [comment]
> The section 3 maintenance medbay has two surgery rooms that can already spawn existing advanced surgery tools. Might be an idea to add these new ones to that spawn pool too.

Maybe, but for the time untill Tor can do the sprites and someone a bit more understanding of the balance of them ill be making them blacklisted

**Comment by Jamini** [comment]
> The section 3 maintenance medbay has two surgery rooms that can already spawn existing advanced surgery tools. Might be an idea to add these new ones to that spawn pool too.

That's a good point. I had forgotten that advanced surgical tools already spawn randomly. Including laser scalpels. Hm

No need to blacklist them, tbh. Just make sure they have the same tags that the advanced scapel has.

**Comment by Jamini** [comment]
Actually, here. I can help you with it now! One moment.

**Comment by Trilbyspaceclone** [comment]
Anything more request wise?

**Comment by Jamini** [comment]
Tori had a few things he wanted to talk on. I'll ping him.

**Comment by Trilbyspaceclone** [comment]
They still going to contact me?

**Comment by Michiyamenotehifunana** [comment]
Heeey, Trillby. I know this kinda sucks but like, this PR kinda became redundant since we got some things merged, and while I do appreciate the attempt, the multitool sprite just isn't really visually distinct enough and doesn't follow the color scheme that all the other tools do.

**Pull request closed without merging**
