### PR TITLE
fixes dorm spawns

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Fixes the dorm spawns
Now you span in the elevator. There is a call button inside the elevator to go back to the ship proper should it be down

## Why It's Good For The Game

Whoops dorm spawns

## Changelog
```changelog
fix: dorm spawns fixed
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
This is gonna cause people to clock out as soon as they spawn in if someone is currently going up the elevator...

**Comment by ShadzFen** [comment]
It will also cause players to see the objects on the floor disappear! My shitty code will be yet again exposed >:c

**Comment by Jamini** [comment]
It'll be rare!

**Review by ShadzFen — APPROVED** [review]
Temporary fix for now.

**Review by ShadzFen — APPROVED** [review]
If it's tested and works, cool. I'll clean up the code that is left over on the call button later.

**Pull request merged**
