### PR TITLE
Medbayadjustment2

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Remaps medbay to be Occulus medbay!
Adds Psychiatrist locker,
Adds some pill types
Adds blood bag lacker

image
image
level3
level4
level5

## Why It's Good For The Game
New RP rooms, provides better work flow for medical staff, and is better suited towards RP then the current Eris Medbay.

## Changelog
```changelog
add: New Medbay Map
add: Psychiatrist locker
add: New pillbottle types
Add: blood bag locker
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
Right, after several hours of going through the new Medbay meticulously, and walking through it on a private server while comparing it to the rest of the ship and the original Nanotrasen department layouts standard, I've written up a list of changes that need to be made. Every single one of these change requests has been discussed, reviewed and approved by our Head Developer.

- [ ] Remove the light switch in virology. It doesn't need one and it causes problems with turning the lights on in the double airlock.
- [ ] Fix the defined area for the Morgue. It causes issues by automatically turning on the lights when walking through the maintenance shaft south of it, without entering the room.
- [ ] The bathroom walls that are adjacent to maintenance need to be changed to reinforced walls.
- [ ] Patient Room A needs a fire alarm, since it has an air alarm.
- [ ] Patient Room B needs a fire alarm, since it has an air alarm.
- [ ] Change Patient Wing hallway light fixtures from small to large in order to fit the rest of the Nanotrasen department style.
- [ ] Remove the light switch in the Bio-Regeneration Laboratory. This room is in the most public deck of medbay and should be well lit up in order to feel more welcoming and relaxing for patients, as well as to fit the rest of the Nanotrasen department style.
- [ ] Remove the light switch in the CMO office. This room is fully visible from the middle of medbay, in the most public deck of medbay and should be well lit up in order to feel more welcoming and relaxing for patients, as well as to fit the rest of the Nanotrasen department style.
- [ ] Replace catwalks for regular floor with White Cargo Tile under the airlocks in the cryocell cooling room.
- [ ] Change the walls adjacent to every set of stairs in medbay to be reinforced walls in order to stay in line with the entire ship's consistency of having reinforced walls adjacent to staircases.
- [ ] Please add 4 medical bounced radios to one of the tables in the equipment locker room, similar to how engineering has 4 medical bounced radios in their EVA room.
- [ ] Change the small light fixture in the Security Post to a large light fixture in order to fit the rest of the Security Posts on the ship.
- [ ] Change the small light fixture to the east of the chemistry room to a large light fixture in order to fit the Nanotrasen department style.
- [ ] The airlock to the room to the west of Chemistry needs to be renamed to Chemistry Storage.
- [ ] Chemistry Storage has no Monkey Isolation room and has a double wall to the west of it. Figure out a way to get rid of the double wall and fit in a small monkey isolation room, even if it has to be a 1x2.
- [ ] Deck 4 is the floor that houses the psychiatrist's room. Remove the light switches from both the psychiatrist's office and the chemistry room in order to keep the patient's visible area lit up at all times. This makes it more welcoming and relaxing for the patient and stays in line with medbay being lit up properly.
- [ ] Remove the light switch from the medical break room. This room has 4 windows and should be lit up at all times to stay in line with the rest of the Medbay's open rooms.
- [ ] The Recovery Ward has a newscaster in a window. This needs to be fixed.
- [ ] Medbay entrance has the Second Section Hallway APC not adjacent to a wall, and is floating instead. This needs to be fixed.
- [ ] The south stairs in the lobby are trying to go up, rather than down. This needs to be fixed.
- [ ] A vast majority of the airlocks throughout Medbay do not have the standard White Cargo Tile underneath them. This is completely out of consistency with the rest of the ship. Every single instance of this needs to be fixed.

Overall the rest of the map changes look pretty good.

**Comment by RadiantFlash7** [comment]
Just want to ask about a couple things really quickly, I can easily more or less do all of this with no issue.
> 
> * [ ]  Remove the light switch in virology. It doesn't need one and it causes problems with turning the lights on in the double airlock.

I didn’t modify virology at all, so I believe that light switch was Eris’s?, and it’s one of the absolutely least used rooms in medical thats fairly large. Would it make more sense to move the light switch to the airlock, instead of removing it?
> * [ ]  The bathroom walls that are adjacent to maintenance need to be changed to reinforced walls.

I can slap reinforce walls on these, Though I would like to leave atleast one normal wall, as a route to break in through for people trying to break into medical. If thats not good, I can just reinforce it all, but felt like it might be good to have atleast one weak entry that wasn’t an airlock. I know Eris has reinforced walls to maintenance everywhere, but I’ll admit, I’m more accustomed to seeing normal walls like in most other code bases.

> * [ ]  Chemistry Storage has no Monkey Isolation room and has a double wall to the west of it. Figure out a way to get rid of the double wall and fit in a small monkey isolation room, even if it has to be a 1x2.

Legitimate question: Does chemistry need a monkey isolation room?
What Do you use it for? Monkey virology-anti body stuff goes to virology. The only thing I could see is.. testing out chemicals on a subject, but isn’t that more sciences shtick then medical chemistries?

> * [ ]  Deck 4 is the floor that houses the psychiatrist's room. Remove the light switches from both the psychiatrist's office and the chemistry room in order to keep the patient's visible area lit up at all times. This makes it more welcoming and relaxing for the patient and stays in line with medbay being lit up properly.

This is probably the one room I disagree with you on the light switch being a thing. The psychiatrist is meant to have privacy shutters/polarized windows, and some psychiatric work would involve having lights dimmed/off.
I’d like to request we keep the switch in this one.

**Comment by ShadzFen** [comment]
> I didn’t modify virology at all, so I believe that light switch was Eris’s?, and it’s one of the absolutely least used rooms in medical thats fairly large. Would it make more sense to move the light switch to the airlock, instead of removing it?

Our original virology has no light switch, so you must have accidentally put one in there by accident. Having a light switch in the double airlock instead of the virology room will mean that if the lights go off while someone is in virology they have to walk all the way into the double airlock to turn them back on. It's problematic for such a large room and should just be removed for the sake of staying consistent.

> I can slap reinforce walls on these, Though I would like to leave atleast one normal wall, as a route to break in through for people trying to break into medical. If thats not good, I can just reinforce it all, but felt like it might be good to have atleast one weak entry that wasn’t an airlock. I know Eris has reinforced walls to maintenance everywhere, but I’ll admit, I’m more accustomed to seeing normal walls like in most other code bases.

That's fine, you can add maybe a normal wall behind the toilets or whatever, but please reinforce the rest.

> Legitimate question: Does chemistry need a monkey isolation room?
What Do you use it for? Monkey virology-anti body stuff goes to virology. The only thing I could see is.. testing out chemicals on a subject, but isn’t that more sciences shtick then medical chemistries?

Discussed this with Tori last night and we came to the conclusion that it should have one. You added a psychiatrist room for the sake of more RP. A chemist who is new to Erismed might want to RP testing their mixed chemicals on monkeys and see the possible effects before doing tests with humans. Besides that, we shouldn't remove a room just because it wasn't used excessively. 

> This is probably the one room I disagree with you on the light switch being a thing. The psychiatrist is meant to have privacy shutters/polarized windows, and some psychiatric work would involve having lights dimmed/off.
I’d like to request we keep the switch in this one.

That's a fair point. In that case, remove only the light switch in the chemistry room, as this room should always be lit up since it's visible from the psychiatrist room when the shutters are up. Besides that it's a large room, and light switches are known to randomly turn off due to their problematic coding, which can prove frustrating.

**Comment by Jamini** [comment]
>  Please add 4 medical bounced radios to one of the tables in the equipment locker room, similar to how engineering has 4 engineering bounced radios in their EVA room.

@ShadzFen  I would suggest this only be two. Only Paramedics require bounced radios since that slot is the only first responder role in medical. Other doctors are generally expected to remain within medical and use the intercoms there, which have the medical channel.

Engineers have four because we have more engineer slots and all of those slots are first responder roles.

**Comment by RadiantFlash7** [comment]
Changes made.

**Comment by RadiantFlash7** [comment]
Bed changes tested and good to go! No longer giving insane levels of insight!

**Review by Jamini — APPROVED** [review]

**Comment by Jamini** [comment]
Alright, at least two, three of us have went over this in decent depths. Further changes can be done after it is live. Merging.

**Pull request merged**
