### PR TITLE
Pouch and belt storage nerf

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Storage Pouches, belts, and toolboxes take up more space depending on how full they are.
Small, Holding, and Ammo pouches are exempt from this.
Sheaths now fit in your pockets, on your back, and in suit storage
Baton Holsters can now fit flashlights, spades, and stacks of rods
All swords and knives now fit in sheaths

## Why It's Good For The Game

Stacking storage items allows people to get stupid amounts of storage on their person. Now putting your pouch or toolbelt in your bag has downsides.

Buffs a few less-used storage items by making them more desirable.

## Changelog
```changelog
balance: item belts now take up more space inside another container depending on how full they are
balance: most pouches now take up more space inside other containers depending on how full they are
balance: all swords now fit in sheaths
balance: baton holsters now hold more items
balance: sheaths now fit in your pockets, on your back, or in your suit storage!
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
unsure if nerfing the mat/tool pouches is wise. barely used, as-is.

**Comment by Jamini** [comment]
> unsure if nerfing the mat/tool pouches is wise. barely used, as-is. good stuff otherwise me thinks?

I did consider that! I wouldn't say barely used, they are more just under-utilized, especially after the recent buffs! AFAIK, most people don't toss tool/med pouches into other storage items when they are used because they contain items you want to have immediate access to. (I.e. Tools/Medicine)

I'll keep an eye on them and see.

**Review by zackerycodestoo — CHANGES_REQUESTED** [review]
If your backpack is full and you insert items into an empty pouch, the pouch will still get bigger and the container (the backpack) doesn't complain about it until you try to take the pouch out and put it back in again. Can you include a check for that? 

image

Pictured above: a full medical satchel with an empty medium pouch

image

Pictured above: A full medical satchel with a medium pouch filled to the brim after inserting it

Would it also be possible to include code for the inventory list to also update the size of the pouch (visually) as things are being added to it without closing and opening the satchel again?

**Comment by Jamini** [comment]
> If your backpack is full and you insert items into an empty pouch, the pouch will still get bigger and the container (the backpack) doesn't complain about it until you try to take the pouch out and put it back in again. Can you include a check for that?
> 
> image
> 
> Pictured above: a full medical satchel with an empty medium pouch
> 
> image
> 
> Pictured above: A full medical satchel with a medium pouch filled to the brim after inserting it
> 
> Would it also be possible to include code for the inventory list to also update the size of the pouch (visually) as things are being added to it without closing and opening the satchel again?

Not possible due to how backpack code works. It would be a separate, much more involved fix. Other operations that change capacity taken (toolmods) do the same thing.

**Review by zackerycodestoo — APPROVED** [review]
Changes requested are beyond the scope of this PR

**Pull request merged**
