### PR TITLE
Anomoly Lab Map Tweak

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Adds an air alarm to the anomaly lab.
Adds inflatables to the anomaly lab
Removes the duplicate AED cabinet in medical
Added fire extinguishers to the anomoaly lab
Fixed anomoly lab disposal line

image

## Why It's Good For The Game

QoL map stuff things

## Changelog
```changelog
tweak: adjusted anomoly lab
fix: Anomoly lab, misc research, xenobotany disposals now work
fix: removed duplicate AED closet
```

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Can we swap out the laptop in the anomaly lab for one of the old computers thats not ID locked? So we can access the local air alarms?

**Comment by Zenitheevee** [comment]
Hey jams i dont mean to push stuff on you but
Could you deal with the very minor issue of the anomoly lab not having any disposal pipes within it, despite all 3 disposal bins nearby all linking to the pipe at its airlock? 
image

**Comment by Jamini** [comment]
> Can we swap out the laptop in the anomaly lab for one of the old computers thats not ID locked? So we can access the local air alarms?

I cannot as such a console would allow scientists unrestricted access to air alarms *and* all of that stuff was ported over to modular computers. AFAIK

**Comment by Jamini** [comment]
Disposals fixed

**Comment by RadiantFlash7** [comment]
> > Can we swap out the laptop in the anomaly lab for one of the old computers thats not ID locked? So we can access the local air alarms?
> 
> I cannot as such a console would allow scientists unrestricted access to air alarms _and_ all of that stuff was ported over to modular computers. AFAIK

At one point baycode had isolated laptop atmosphere controls specifically for those air alarms only. If they don’t exist anymore, don’t worry about it. I’ll look into fiddling with it, when I see about whats causing the exotic particle harvestor to break

**Pull request closed without merging**
