### PR TITLE
Normalizes species temperature discomfort levels to reduce chatspam

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request
Exactly what it says on the tin. Tajaran will no longer prickle in the heat x256.

## Changelog
```changelog Toriate
tweak: Normalized species temperature discomfort levels to reduce chatspam
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
This isn't normalizing it, this is straight up removing it, is it not?

**Comment by Michiyamenotehifunana** [comment]
Exactly.

**Comment by ShadzFen** [comment]
Adjust the value to 303. That's 303 Kelvin, 30 Celsius, for Tajaran heat discomfort.

**Review by ShadzFen — CHANGES_REQUESTED** [review]
Check the last comment

**Comment by Michiyamenotehifunana** [comment]
Taj treshold set to 303K, unathi tresholds expanded by 5K in both directions.

**Comment by ShadzFen** [comment]
W-Why...? There was no issues with the unathi temperatures, was there?

**Review by ShadzFen — APPROVED** [review]
Finally! Non-modular, small variable change. Good to go

**Pull request merged**
