### PR TITLE
Fixes Energy Armblade Augmentor

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

I hate coding
image
This one thing broke it.
Why was it there? I dont know.

## Why It's Good For The Game

Fixes borked thing

## Changelog
```changelog
fix: E_armblade now actually spawns with the augment inside it... I hate code.
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
You didn't really... change anything. Are you sure you uploaded the correct commit?

**Comment by Zenitheevee** [comment]
> 
> 
> You didn't really... change anything. Are you sure you uploaded the correct commit?

image
This space is literally what killed it, I dont know how or why, But further testing proved it fixes it (And i do implore you to try yourself if further skepticism is brought up)

**Review by ShadzFen — APPROVED** [review]
Usually DM doesn't let you compile if you indent incorrectly. Odd. Anyway, if you've tested and you're sure it works, I'll trust you. Modular changes, all good.

**Comment by Zenitheevee** [comment]
Trust me, I wish i knew how this got by the loops it did, both in code and testing, as the materials were not my personal addition.

**Pull request merged**
