### PR TITLE
Completely Reinvents Telescience

### PR DESCRIPTION
**Pull request by fludd12**
## About The Pull Request

This is a complete reinvention of telescience from the ground up. Rather than being based on arbitrary trigonometric calculations and otherwise allowing effectively instant transportation from point A to point B with no counter, this system is more open to people without graphing calculators on hand, but it also takes a fairly long amount of time to work, and has more restrictions.

**Setup:**
image
A telescience setup will require a telepad, a telescience console, and between one and four relays positioned cardinally around the telepad. Each relay takes one crystal, and increases the range at which a telescientist can non-wastefully perform their job.

**User Interface:**
image
Telescience allows you to teleport to specific coordinates per normal, but it now has the additional feature of letting you target teleporter beacons for ease of access. By targeting a teleporter beacon, you are able to skip the pathfinding trial and error!

**Pathfinding:**
image
In order to teleport without selecting a beacon, you must do the Pathfinding minigame! This is basically Mastermind, but the length of the code is determined by the distance you're hoping to teleport! Most places on the ship will require only one to three digits, but anywhere off ship requires a minimum of four!

**Relays:**
image
You always have to have at least one relay with a crystal inserted in order to teleport, but trying to input more digits in Mastermind than you have working Relays damages the bluespace crystals very rapidly.

**Path Traversal:**
image
After successfully completing the Pathfinding minigame (or bypassing it by selecting a beacon to teleport to), you have to wait for some time before the portal opens. During this time, people nearby the targeted location will see and hear unique effects betraying your bluespace interference! If you want to shorten the time it takes to teleport, increase your cognition, use fewer relays, and upgrade your relays with high efficiency parts.

## Why It's Good For The Game

Existing telescience has always been a bit of a problem child -- there's a reason it is unavailable on most servers, nowadays. Since there were people voicing concerns about its efficacy and suggesting it be put on the chopping block, I wanted to try my hands at the 'improve, don't remove' mindset.

## Changelog
```changelog
refactor: Telescience has been completely refactored. Please feel free to take a look! It should be much easier for the average player to get into, now.
```

Right now, these sprites are very _codersprite_-y. Especially the telepad. Better sprite work is always appreciated!

### CODE REVIEW

**Review by Jamini — DISMISSED** [review]
Fel, have I mentioned that you terrify me sometimes?

Highly modular change, everything properly marked. nothing egregious at first glance. Considering the author almost certainly extensively tested. I see nothing outright blocking us from getting this in, however I do humbly request that you stay alert for any bugs that people find with the new version of telesci.

**Comment by fludd12** [comment]
I sort of hope bugs are found, to be honest -- that'd mean that people are using it in the first place! That said, thank you so much.

**Comment by fludd12** [comment]
Review invalidated by most recent commit -- it's just map changes, though, so I assume the review of the code specifically still stands.

**Review by Jamini — DISMISSED** [review]

**Comment by fludd12** [comment]
Oh god actual issues. It should be fine, now.

**Review by Jamini — APPROVED** [review]

**Review by Jamini — APPROVED** [review]

**Pull request merged**
