### PR TITLE
Hotfix

### PR DESCRIPTION
**Pull request by GremlingSS**
### YEAH SORRY ABOUT THAT
It works perfectly fine on my end plus complete oversite.

## Changelog
```changelog
fix: hotfix to fix spawning issue
```

### CODE REVIEW

**Review by Michiyamenotehifunana — APPROVED** [review]
Yep, that's the problematic code right there. Should be good.

**Comment by GremlingSS** [comment]
it's pretty dumb that that if(client.prefs.relations.len) is always true but 🤷

**Comment by GremlingSS** [comment]
wait no I brainfarted sorry, it's not always true, but if it is true, then there's errors. because relationships don't initialise and cause the runtime.

**Comment by RadiantFlash7** [comment]
JustEriscode.png

**Comment by Jamini** [comment]
Relationships are ported bay code. It's Eclipse stuff, not Eris.

**Comment by RadiantFlash7** [comment]
🙀

**Pull request merged**
