### PR TITLE
Adds a fight club to maint.

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

Maint fight club. Next to the dorms. Oh, yes.

## Why It's Good For The Game

Do you not want places to murder eachother in?
Pics:
image
image

## Changelog
```changelog
add: new fightclub room in maints, near dorms
```

### CODE REVIEW

**Comment by zackerycodestoo** [comment]
Please adjust the changelog blurb -- are there any roach spawners in this room? Just curious, that's not part of the requested changes

**Comment by zackerycodestoo** [comment]
Looks nice -- only discrepancy is that the upper area is considered fore maintenance while the lower area is port maintenance, could that be adjusted?

**Comment by bearrrrrrrr** [comment]
ooops- changelog fixed! And no, there are no roach spawners. as for the areas, I'll see if I can fix that real quick.

**Comment by bearrrrrrrr** [comment]
Lower area will now show up as deck 5 fore maint, inline with top area.

**Review by zackerycodestoo — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
