### PR TITLE
Xenoarchaeology fixes and Remap

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Various misc fixes involving Xenoarchaeology:
Stun batons not triggering anomalies, 
Xenoarch particle harvesting connection fixed,
Adjusts air alarm control in anomaly lab to be science access, and only connect to isolation room air alarms,
Makes Icons for artifacts/anomalies show up a little more frequently on the asteroid.
Also adds new features:
Anomaly containers. Click and drag anomalies into them to transport them without having to worry about their effects going off mid transit. Good for storing anomalies that activate in atmosphere conditions.
Remaps The anomaly lab:
Removes little alley way in favor of expanding the anomaly lab dramatically to give a proper workspace. Also enlargens the miscellanious test area for other uses.

((Also stealth adds doors to medical for a trial run to limit atmos decompression))
image
image

image
image

## Why It's Good For The Game
The Anomaly lab is in an awkward spot in that Eris really just rammed it in there and probably hasn't touched it once since. It's simultaniously cramped, yet completely disorganized and somewhat empty, having not enough space and too much. The remaps much better.
Also, a spot to store anomalies, and separate several actions of Anomaly research in sub rooms is beneficial and pleases my brains desire to organize things.

Also, bug fixes are like, never bad.

## Changelog
```changelog
add: Anomaly Container
tweak: Anomaly lab remap
tweak: Misc lab remap
tweak: makes artifact/anomalies be visible more commonly on mesons instead of once in a blue moon.
balance: Adjusts Anomaly batteries
fix: wrong baton file paths, 
fix: exotic particle harvestor bugs
```

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Note: particle harvestor is bugging the hell out. Working on debugging it's failure at the moment.

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks alright!

**Comment by RadiantFlash7** [comment]
> Looks alright!

I still need to fix exotic particle stuff. I’ve got the harvestor working, but I’m adjusting the batteries to actually work, rather then drain all the usage instantly on barely a second of use

**Review by Michiyamenotehifunana — APPROVED** [review]
Nothing here looks particularly egregious, should be good to go!

**Review by Jamini — APPROVED** [review]
Seems fine, for our extremely high number of Xenoarchologists and anomoalists on the server (1)

**Pull request merged**
