### PR TITLE
Adds the nanite reconstitution apparatus (de-oldifier)

### PR DESCRIPTION
**Pull request by zackerycodestoo**
## About The Pull Request

Now presenting the nanite reconstitution apparatus -- an idea originally devised by RadiantFlash with most of the code from him, finished off by me.

This (mostly) modular code places a new machine, the nanite reconstitution apparatus, in the engineering construction site beside the autolathe. This machine de-oldifies items for a cost in materials.

To de-oldify an item, you require the following:

10 steel
3 plasteel
9 industrial nanites

Furthermore, the machine can be upgraded with stock parts. The following stock parts are used to construct the machine and these are their effects:

Manipulators: Upgraded manipulators will improve the reconstitution speed.
Scanner: An upgraded scanner will reduce the cost of reconstitution (by 20% per level, 40% reduction with a phasic)
Bin: Upgraded bins will increase material storage for steel and plasteel.

The machine does not have wires to modify at this time. At roundstart, the machine has enough materials for three reconstitutions. Uncapped nanites are acquired by processing kraftwerk roaches or other sources.

Finally, the circuitboard to create the machine has been added to the research database.

image
image
image
image

## Why It's Good For The Game

This is a step towards giving engineers something to be able to do without punishing the crew for not having engineers around, and can even de-oldify some equipment that would be otherwise too useless or dangerous to use while old -- rusty atomcells, anyone?

## Changelog
```changelog
add: The nanite reconstitution apparatus (aka de-oldifier) has been installed in the engineering construction site beside the autolathe.
```

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Thanks a ton for finishing what I couldn't.
My only comment on it, is maybe increasing the nanite requirement amount?
lockers with kraftwerks are fairly common, in maintenance, with like 5-6 kraftwerks inside.

**Review by Jamini — DISMISSED** [review]
Kindly remove the research design for this. This is an engineering-only thing. There should be a spare circuit in the CE's locker, but NT should not be able to replicate EES-Only stuff.

**Comment by Jamini** [comment]
Also for the love of god don't put it in that room. Please. Put it near the break room. That room is CBT to get to.

**Comment by zackerycodestoo** [comment]
1. Nanite requirement changed from "uncapped nanites" to "industrial nanobots", cost upped to 9 industrial nanobots per use (that is three kraftwerks to one de-oldify)
2. Starting nanites upped to 30 (9 per use)
3. Removed from research database
4. Spare circuitboard added to CE's locker
5. The Cube room has been made slightly larger. The autolathe and its disks have been moved upstairs, and the NRA has been installed there instead. The construction area now has materials and possible toolmod spawns to replace the moved autolathe, to keep it interesting to visit.

image
image
(No luck on that spawn)

**Review by Jamini — APPROVED** [review]
Excellent. All blockers handled. I look forward to seeing this in-game.

**Pull request merged**
