### PR TITLE
Maps in an underwear drawer, deletes extraneous bar chairs

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request

Exactly what it says on the tin. No more chairs on top of sofas, and the showers now gets an underwear drawer.

## Changelog
```changelog Toriate
add: An underwear drawer has been installed in the showers!
fix: The club should no longer have chairs installed on top of the sofas. The contractors responsible for that particularly innovative solution have been sacked.
```

### CODE REVIEW

**Review by Jamini — APPROVED** [review]
Looks good.

**Comment by ShadzFen** [comment]
Map changes would be appreciated with pictures to show the changes.

**Comment by Jamini** [comment]
> Map changes would be appreciated with pictures to show the changes.

Note really needed in this case since it's a very small PR. You can see which tiles are getting edited.

**Comment by ShadzFen** [comment]
Yes but not everyone can read code. We're not the only ones who check these PRs! When it comes to DMI or map changes, pictures should be standard.

**Pull request merged**
