### PR TITLE
Heating and cooling fixes

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Fixed space heater cell replacement.
Fixed coolant making temperatures absolute zero when shot
- Now coolant reduces the heat in joules in a room by 6000 per unit of coolant

## Why It's Good For The Game

Space heaters will be functional again.
Coolant will no longer make deep maintainence literally impossible to survive in if you accidentally one coolant tank

## Changelog
```changelog
fix: Adjusted connectors within space heaters to properly fit large cells instead of medium, as the cell housing fits large ones!
fix: Theoretical coolant mix has been removed from the light and replaced with coolant that doesn't break the laws of physics. The chemists responsible have been sacked.
```

### CODE REVIEW

**Comment by Jamini** [comment]
image

**Comment by Jamini** [comment]
image

Shooting a tank of coolant in a 12-tile room

**Comment by Jamini** [comment]
Shooting a tank of coolant in a 43 tile room

image

**Comment by Jamini** [comment]
Shooting a tank of coolant in a 155 tile room

image

**Comment by Jamini** [comment]
Shooting a tank of coolant in an arbitrarily large room (deep maint)

image

**Review by zackerycodestoo — APPROVED** [review]
Thank you for documenting all the testing. All looks well, makes sense, and non-modular code is marked

**Pull request merged**
