### PR TITLE
Respriting the Captain's Wardrobe

### PR DESCRIPTION
**Pull request by SigDoesCode**
Changes the captain from blue/gold to black/gold with new sprites for clothing.

## About The Pull Request

This is a biggie. I've changed the sprites for everything the captain has, some are recolors and some are totally new sprites. 

Included are:
New shoes. Black, kind of like the brown shoes. They're good for most command I'd say. 
Resprited gloves. Black and gold. 
New hat. Like the officer's hat but gold. 
New jacket. This one can be buttoned or unbuttoned. 
New jumpsuit. Two colors of blue shirt and black pants. 
New parade jumpsuit.
New fancy coat. Half capes are cool. 
New captain's armor. 
New captain's dress. 
New captain's armor, with a yet to be implemented shielding feature that I need to figure out how to work, but the sprite and armor values work. 

image
The captain from the front with their coat unbuttoned. 

image
A shot of the inventory showing the regular uniform, unbuttoned jacket, gloves, hat, and shoes. 

image
The captain's new greatcoat. 

image
The captain armor on the left and the captain's dress on the right. 

image
The captain in their armor.

image
And lastly the captain's dress on a mob.

There are male and female sprites for the uniforms. Everything else should be fine? 

## Why It's Good For The Game

New captain sprites are cool, plus I was asked to do this a while back.
 

## Changelog
```changelog
tweak: Changed the sprites for the captain's stuff. Now they're fancy! 
```

## Notes:

1. The captain's armor has a commented out block of code that has to do with some armor shielding. I'll be looking at how to work it at some point, but it's just in for now in case anyone wants to get it to work. It's copied from Para, I think, and I tried to annotate it the best I can but I love the idea of the functionality so it's staying in for now.

### CODE REVIEW

**Comment by SigDoesCode** [comment]
I don't know what's going on here with the checks, I didn't touch the map?

**Comment by Jamini** [comment]
cev_eris.dme zzzz_modular/occulus/icons/inventory/uniform/mob.dmi and zzzz_modular/occulus/icons/inventory/uniform/mob_fem.dmi are conflicting

**Comment by SigDoesCode** [comment]
> cev_eris.dme zzzz_modular/occulus/icons/inventory/uniform/mob.dmi and zzzz_modular/occulus/icons/inventory/uniform/mob_fem.dmi are conflicting

Could you explain this to me tomorrow morning? I don't know what's up.

**Comment by Michiyamenotehifunana** [comment]
Closing due to merge of #572

**Pull request closed without merging**
