### PR TITLE
General code fixing

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Finishes up the majority of linting issues. (All Errors cleared, only the #warn for the 513.dm compatibility exist, which doesn't fail linting.)

## Why It's Good For The Game

Stop CI screaming at people via email about failed runs, at least for linting.

### CODE REVIEW

**Review by Jamini — CHANGES_REQUESTED** [review]
Assuming these changes were done by hand and are not ports, every single change from Eris master to our code that isn't in a modular file must be marked as per policy.

I *know* it sucks, but that's how we do it here.

**Comment by Jamini** [comment]
Aside from marking the changes, it looks good though.

**Comment by Shadow-Quill** [comment]
> are not ports

They are ports.

**Comment by Shadow-Quill** [comment]
As a note, after this and #766 are merged, workflows will need to be manually re-run for the other open PRs, unless the author pushes a commit.

**Review by Jamini — APPROVED** [review]

**Pull request merged**
