### PR TITLE
Adds fishing hats

### PR DESCRIPTION
**Pull request by anconfuzedrock**
## About The Pull Request
Adds procedurally generated fishing hats, to show how women and fish feel about you. 80% of them are benign, and the remaining 20% differ between somewhat complex and absurdly long. If your hat is big, it will be taller in-game. Special thanks to my friend Scree for helping, or really most of the work.
image

## Why It's Good For The Game
Funny hat. Very powerful experience to find onna these in a maint loot pile.

## Changelog
```changelog
add: new hats to express how fish and women feel about you
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
OtterFish

**Comment by Jamini** [comment]
I find this hilarious but I'm going to defer to our loremaster on if we should add this.

**Comment by Ikmachek** [comment]
This is so incredibly stupid but you clearly put effort into this so I'm going to have to tentatively approve it.

**Comment by Shadow-Quill** [comment]
Code should be moved to the modular files.

**Comment by Mocha-Not-Latte** [comment]
I hate this, but it's funny.

**Comment by RadiantFlash7** [comment]
My sides....

**Comment by anconfuzedrock** [comment]
> Code should be moved to the modular files, please.

donezo

**Comment by anconfuzedrock** [comment]
hats were so big it was causing errors, I turned down their size a bit and fixed various issues. now with navy and black hat variant colors!

**Comment by bearrrrrrrr** [comment]
this is so good

**Review by Jamini — APPROVED** [review]
Players fear me. Roaches love me. Tajaran pursue me to the ends of the earth, constantly thwarted by inconsequential setbacks, and when they catch up and I ask in an exasperated voice why they respond 'you owe me a credit

**Pull request merged**
