### PR TITLE
Fixes duplicate core implants

### LINKED ISSUE #41: Multiple Soulcrypts are spawning in people
#### Description of issue

Multiple soulcrypts are spawning in players that have the core implant selected

#### Difference between expected and actual behavior

There should only be one

Additionally: Multiple crypts are being implanted in people. It is not a scanner bug!

#### Steps to reproduce 

1. Add a soulcrypt core implant
2. Go into body scanner
3. ???
4. PROFIT!

#### Length of time in which bug has been known to occur

Since we ported over the changes to core implants. This was occurring on the last days on Syzygy too.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request
This PR removes redundant core implant spawning checks in order to make it so that people no longer spawn with 3 cruciforms/soulcrypts. Closes #41.

## Changelog
```changelog Toriate
fix: People should no longer start with 3 cruciforms and soulcrypts jammed into their chest.
```

### CODE REVIEW

**Review by Jamini — APPROVED** [review]
Approving this on the condition that it's tested. Everything is marked properly.

**Comment by Michiyamenotehifunana** [comment]
I did the bare minimum of testing, we'll need to monitor the situation closely after merging and updating.

**Comment by ShadzFen** [comment]
How much is bare minimum? I don't want to merge a PR that breaks soulcrypts entirely from working. As long as you can at least ensure that the soulcrypts still function, I'd be okay with this to be merged.

**Comment by ShadzFen** [comment]
Apparently it's been tested and it's sure to be working. Readying it for merge again.

**Pull request merged**
