### PR TITLE
Nobles start with 5x the regular amount in their accounts

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

I remember someone saying that they wanted to give nobles 10x the starting amount of money when they spawned in, and I felt the motivation so :P

It did seem that 10x was a little too high, so I opted for 5x.

## Why It's Good For The Game

Nobles are probably rich.

## Changelog
```changelog
tweak: Nobles start with 5x the normal money amount.
```

### CODE REVIEW

**Review by Michiyamenotehifunana — APPROVED** [review]
Approving on the basis that the code's solid.

**Comment by Jamini** [comment]
Merging it, but I said x10 for a reason.

One must remember that 30cr is roughly equal to 1USD. Plus the noble perk has a pretty stiff downside.

**Comment by bearrrrrrrr** [comment]
10x is a hilariously stupidly high amount. 5x is already redic tbh. starting with 30,000 credits LMFAO

**Comment by Jamini** [comment]
10,000cr isn't really that much in the grand sceme of things. Nobles are supposed to be rich, after all.

Most jobs start with wage* (1.5 - 3.5) money 

Which averages to 1,850cr (Because most jobs may more money than they should)
Assistants start with an average of 800 cr
Club workers 750
Club manager 3000

On average non-pistol guns are around 2k, most crates are 2-4k, soulcrypts are 20k, voidsuits are 2-4k, hardsuits are 6k

It's not outside of the realm of realism that nobles could start with 18k (8k for deckhands, 30k for club managers, 28k for noble commanders).  This goes double when we compare it to the two other "extreme" origins: Rejected Genius and Artist.

Rejected Genius: Level up at 150% rate. Often capping out on certain stats within two hours. The downside they have is identical to noble.
Artist: Level up at 150% rate, and have a reliable source of good oddities and cashflow. The downside they have is they can't stack insight.

Noble has long been left in the dust compared to those two. Strong oddities are more and more common with people learning how to use the cube and the addition of artist and MEK seals. Weapons also have gotten more prolific and much easier to get. The Noble perk as it was (Which simply gave you a weapon, normally a melee weapon, and a mid-tier oddity in exchange for no sanity cap loss *and* being eligable for assassination contracts.) was frankly mostly garbage. Giving nobles a reliable cushion of cash to spend not only buffs the perk, but adds more proper *buyers* to the economy.

**Pull request merged**
