### PR TITLE
rope

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request

rope

## Why It's Good For The Game

rope

## Changelog
```changelog  Toriate
add: rope
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
Improve your PR, please. This looks like a shitpost PR. Also add some pictures of the sprites.

**Review by Jamini — APPROVED** [review]

**Comment by Jamini** [comment]
Wait this isn't what i meant to approve. What

**Comment by Jamini** [comment]
:Jamero:

**Comment by ShadzFen** [comment]
Good job lmao

**Comment by Jamini** [comment]
Plz fix the PR tori, it's fine but we need to set a good example

**Comment by Jamini** [comment]
F M L

**Pull request merged**
