### PR TITLE
Added Solgov uniforms to loadouts

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Adds the solgov uniforms to loadouts

## Why It's Good For The Game

Hey sprites! Plus some organizing of loadout stuff for Occulus

## Changelog
```changelog
add: Solgov dress uniforms added to loadouts
admin: moved syzygy custom gear icons to proper location
admin: moved syzygy loadout dms to occulus folder
admin: merged syzygy and occulus loot blacklists
```

### CODE REVIEW

**Review by zackerycodestoo — CHANGES_REQUESTED** [review]
Similarly to #377, would you be able to split out the loadout and blacklist changes? Both for organizational reasons (the pull title does not mention blacklist changes) and in the event that for some reason one part of the pull needs to be reverted, the other part is unaffected

**Comment by Jamini** [comment]
> Similarly to #377, would you be able to split out the loadout and blacklist changes? Both for organizational reasons (the pull title does not mention blacklist changes) and in the event that for some reason one part of the pull needs to be reverted, the other part is unaffected

The blacklist is not being changed. The two blacklist files we have are being merged. There is no reason to separate them. It's a purely administrative change.

**Comment by zackerycodestoo** [comment]
> > Similarly to #377, would you be able to split out the loadout and blacklist changes? Both for organizational reasons (the pull title does not mention blacklist changes) and in the event that for some reason one part of the pull needs to be reverted, the other part is unaffected
> 
> The blacklist is not being changed. The two blacklist files we have are being merged. There is no reason to separate them. It's a purely administrative change.

It is a purely administrative change but the changes to `loot_spawn_blacklist.dm` are not directly related to the addition of uniforms to the loadouts, unless I am missing something very obvious. They should be in a separate pull for organizational reasons.

**Comment by bearrrrrrrr** [comment]
i'mmm unironically not a huge fan of this. doesn't really make IC sense to have someone stroll around in solgov fatigues or dress formals on the ship...? they're private contractors, not solmarines lmao.

**Review by Michiyamenotehifunana — APPROVED** [review]
Nothing looks out of the ordinary.

**Pull request merged**
