### PR TITLE
Sanity Screen Effects

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Having low sanity will now show a screen effect, instead of being limited to the sanity eye on the right side of the screen.
Sprites made by Toriate.

## Why It's Good For The Game

More noticible way of seeing you have low sanity, while still remaining relatively:tm: unhindering to gameplay.

## Changelog
```changelog
add: Losing sanity now has a more visual indication, with sprites made by Toriate.
```

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
I owe you, so much for doing this. I've been talking about this as a feature for /months/
But haven't had the time or drive to look into it

**Comment by Shadow-Quill** [comment]
> I owe you, so much

🔥🍫

**Comment by Jamini** [comment]
My only request is an in-game screenshot of the sanity effects, before we merge this. Codewise it's fine, but if the visuals are too distracting I'd like to catch it early.

**Comment by Shadow-Quill** [comment]
> My only request is an in-game screenshot of the sanity effects, before we merge this. Codewise it's fine, but if the visuals are too distracting I'd like to catch it early.

Going to have to wait for more noticeable sprites for now.
At the moment, they're practically invisible, except for _some_ visibility when you're <20 sanity

**Comment by Jamini** [comment]
Cleaning this up since it's been open for over six months. Feel free to reopen it when its ready to be reopened.

**Pull request closed without merging**
