### PR TITLE
Rebalances Longsword

### PR DESCRIPTION
**Pull request by Mocha-Not-Latte**
## About The Pull Request
modular edit to rebalance the longsword from ITEM_SIZE_SMALL to ITEM_SIZE_NORMAL

## Why It's Good For The Game
You can no longer shove a big boy sword into your pockets

## Changelog
```changelog
balance: Changed Longsword to Bulky item size.
```

### CODE REVIEW

**Review by zackerycodestoo — CHANGES_REQUESTED** [review]
Please mark non-modular changes with something saying it was changed by Occulus, like `// OCCULUS EDIT` appended to the end of line 23.

Also, this fix is the perfect candidate for learning how to make a modular change -- do you want to know how?

**Review by zackerycodestoo — DISMISSED** [review]
Looks good!

**Comment by Jamini** [comment]
Please confirm that sheathes still work for these before I merge this.

**Comment by Jamini** [comment]
Also it should probably be ITEM_SIZE_NORMAL since longswords are explicitly not nearly as big as a claymore or fireaxe.

**Comment by Mocha-Not-Latte** [comment]
> Also it should probably be ITEM_SIZE_NORMAL since longswords are explicitly not nearly as big as a claymore or fireaxe.

WOrks with sheaths

**Review by Jamini — APPROVED** [review]
:+1:

**Pull request merged**
