### PR TITLE
Fixes Brigador Firemodes

### PR DESCRIPTION
**Pull request by IrkallaEpsilon**
## About The Pull Request

Brigador firemode fixed

## Why It's Good For The Game

Bridge 'Armory' Plasma Pistol is back to how it was prior svalin rework and gets its less lethal firemode back while being able to swap to 'lethal'.

## Changelog
```changelog
fix: Brigador Plasma Pistol got less lethal mode back.
```

### CODE REVIEW

**Review by ShadzFen — DISMISSED** [review]
Looks fine. Just try to keep the PRs more consistent in the future. Like, straight to the point you know? Makes it easier to read, a lot quicker to review. Modular changes, all good.

**Review by Michiyamenotehifunana — DISMISSED** [review]
You should actually delete the entire duplicate entry instead of whatever this halfassed change is.

**Comment by IrkallaEpsilon** [comment]
Give me a sec, fixing whatever that vestigal stuff at top is.

**Comment by IrkallaEpsilon** [comment]
Vestigal stuff at top removed. I do think the icon states are required for the sprite updates we have for when you put in an atomcell and what not. Would it break things if we move that one down to the brigador entry?

**Review by Jamini — APPROVED** [review]

**Comment by Michiyamenotehifunana** [comment]
The vestigial stuff at the very top was all that was needed for it. You're just tacking things onto an accidental duplicate entry.

**Review by Jamini — APPROVED** [review]

**Review by ShadzFen — APPROVED** [review]
Now it's good to go. Good job spotting that Tori, I totally missed it.

**Review by ShadzFen — APPROVED** [review]

**Pull request merged**
