### PR TITLE
adds my greatest regret: the AR .30 Kalamiti

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request
3, 2, 1, _**GO**_

Adds a new craftable weapon, the AR .30 Kalamiti, built using the base AK47 makeshift. Greatly lowered size, zoom function, fully automatic, and doubles in price! In exchange, the gun becomes genuinely unusable.

## Why It's Good For The Game

~~Dunno.~~ people like cursed/unconventional gun options. 

## Changelog
```changelog
add: Oops.
```

image

### CODE REVIEW

**Comment by Awesome4Real** [comment]
does it have the same functionality of the AK-Makeshift where a screwdriver can change the ammotype from .30, .25, and .20?

**Comment by bearrrrrrrr** [comment]
> does it have the same functionality of the AK-Makeshift where a screwdriver can change the ammotype from .30, .25, and .20?

yes! the text is slightly altered to be more in-line with the finished product, too.

**Comment by SigDoesCode** [comment]
What do you mean by genuinely unusable? This looks like fun.

**Review by Jamini — APPROVED** [review]
You had me in stitches. I cannot wait to see how bad this is in-game.

**Pull request merged**
