### PR TITLE
Small office changes to Cargo and Medbay

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Modifies the cargo desk, merchant office, and medbay into something a bit more usable
Adds a disk toaster to the science lab
Moves the obelisk in the chaplain's office.

image

image

image

## Why It's Good For The Game

Small QoL change to a few popular areas on the map. Also horny barriers so people don't need to watch a certain merchant [REDACTED] with his [REDACTED]

## Changelog
```changelog
tweak: Cargo office
tweak: Merchant office
tweak: Medbay lobby
tweak: disk toaster in science
tweak: moved chaplain obelisk
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
double-double wall in medbay with a window leading into it. looks very, very bad.

**Comment by Michiyamenotehifunana** [comment]
I demand an official statement regarding the existence of the double wall!

**Comment by Jamini** [comment]
> I demand an official statement regarding the existence of the double wall!

Double wall is required to avoid an even larger change to the lobby itself. Also a number of pieces of wall equipment are on all sides of it.

It also looks fine smh.

**Comment by Jamini** [comment]
image

**Review by ShadzFen — APPROVED** [review]
map code can (and should) suck my left nut. Good to go

**Pull request merged**
