### PR TITLE
Unbuggered The Cube Examine

### LINKED ISSUE #133: Typo on The Cube item
#### Description of issue
The Cube item in Engineering has a typo.
The blue text at the bottom says "The The Cube has been feeded 0/5 times"

#### Difference between expected and actual behavior
Feeded instead of fed
The The Cube

#### Steps to reproduce 
Spawn a The Cube or find the one in the catwalk above engineering. Examine.

#### Specific information for locating
See steps to reproduce. ^

#### Length of time in which bug has been known to occur
Unsure, just noticed it today when examining items in display cases.

#### Client version, Server revision & Game ID
Server revision: master - 2021-01-09
ebe09579a9d6ee4664a75535ca62b6b4b0fa9d4e

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

### PR DESCRIPTION
**Pull request by Leon9621**
## About The Pull Request
Updates The Cube's examine text.

Specifically, it's been changed from "The the cube has been feeded x/5 times." to "The Cube has been fed x/5 times."

Fixes #133  

## Why It's Good For The Game
Grammar mistakes ruin my immulshuns and now I have the power to fix it.
But for real, grammar mistakes are Not Good and should be fixed

## Changelog
```changelog
spellcheck: fixed a few typos
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
feeded

**Review by ShadzFen — APPROVED** [review]
All looks good. The DME changes are fine, it's just reordering the list alphabetically. Seems the recent PR that added `gear_tweaks.dm` wasn't ordered correctly. Non-modular, marked.

**Review by Jamini — CHANGES_REQUESTED** [review]
Can you remove/revert your changes to cev_eris.dme? You aren't adding or removing files here.

**Comment by Jamini** [comment]
> All looks good. The DME changes are fine, it's just reordering the list alphabetically. Seems the recent PR that added `gear_tweaks.dm` wasn't ordered correctly. Non-modular, marked.

NO. this is NOT good. Load order matters for a handful of VERY IMPORTANT things. Chief among them markings, hairstyles, and the order of tabs in chargen.

**Pull request merged**
