### PR TITLE
Fixing undies, also cleans up character setup.

### PR DESCRIPTION
**Pull request by GremlingSS**
## About The Pull Request
Who I am is totally not important. I am just a random person.
I come to provide some quick changes to your code. Things which contain the following:

- [x] Fixing undies 
- [x] Disable matchmaking
- [x] Merging the tail/ear/size and whatnot tab (originally virgocode's tab) into the general tab
- [x] Clearing out tabs which isn't used such as the matchmaking tab.
- [x] ~~Preview moved to right hand side of character setup window.~~

## Why It's Good For The Game
idk why does underwear even exist in this game, can't we just like, be nudists or something? 🤔

Matchmaking is being disabled cause apparently you don't use it, if it's removed from character setup but is still in, if someone corrupts the playerdata it can mess up and it's a security step. Just an extra file you can untick when needed, no biggie.

## Changelog
```changelog
fix: Fixed underwear color being additive instead of multiplied
tweak: Adjusted the character setup page. yes.
tweak: Disabled matchmaking
```

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Uh! Okay! No questions, mysterious underwear providing stranger!

**Comment by cebutris** [comment]
> idk why does underwear even exist in this game, can't we just like, be nudists or something? 🤔

they always tell me no when i ask this

**Comment by GremlingSS** [comment]
> > idk why does underwear even exist in this game, can't we just like, be nudists or something? 🤔
> 
> they always tell me no when i ask this

MyJiKR 1

**Review by Jamini — DISMISSED** [review]
Looking it over, nothing suspicious. Unlike you! Unknown suspicious person. What's your story? 

:knifetomeetyou:

**Comment by GremlingSS** [comment]
> Looking it over, nothing suspicious. Unlike you! Unknown suspicious person. What's your story?
> 
> :knifetomeetyou:

c:
I'm just an old SS13 player who's kinda went dead. I worked on ARFS a long long time ago and that's about it.

**Comment by GremlingSS** [comment]
I'm unable to do the preview on the right hand side of the screen like I've seen on another codebase. There's some voodoo magic line of code which sets the obj/effect/screen to be on the right hand side of the entire window and I can't find it. I also can't find a commit about it on the github repos.

**Comment by Jamini** [comment]
That's fine, I'm personally not a fan of that look anyway.

**Review by Jamini — APPROVED** [review]

**Pull request merged**
