### PR TITLE
custom loadout names/descriptions

### PR DESCRIPTION
**Pull request by Greenjoe12345**
## About The Pull Request

This PR adds the ability to set a custom name and description to loadout items, like on Polaris and Aurora.

## Why It's Good For The Game

customization of player loadout items is good.

## Changelog
```changelog
add: Custom loadout names and descriptions
```

### CODE REVIEW

**Review by Jamini — COMMENTED** [review]
/datum/gear_tweak/custom_name/get_metadata(var/user, var/metadata)

This proc needs to match the one on /datum/gear_tweak/get_metadata() (I.E. It needs a var/data arg) in order to pass CI.

**Comment by ShadzFen** [comment]
Oh... Nice. That worked. All I did was add `var/title` to the get_metadata procs and it fixed the CI failure. 

image
image


This PR is tested and full working. The only issue I found was that apostrophes show up as &#39; instead of an apostrophe. 

image

**Comment by Jamini** [comment]
image

Can you fix this real quick? Just grab the current *.dme file, re-tick the new files in dreammaker, and recompile?

**Comment by ShadzFen** [comment]
Strange... I did that already. Lemme do it again, maybe github is being gay.

**Review by Jamini — COMMENTED** [review]
This had better not break anything Shadz

**Review by Jamini — APPROVED** [review]
approving

**Pull request merged**
