### PR TITLE
I Can't Believe It's The Perma Update!

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

Updates perma prison, increasing the size and removing the cameras from the toilet and shower. Tangentally, also removes the cameras from the public shower room since it was the same sort of **bit.** 

**IMPORTANT EDIT: Also removes the suicide booth and replaces it with a cryopod.**

## Changelog
```changelog
tweak: changed perma layout, enforced privacy laws
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
pics below in a sec, as always:

**Comment by bearrrrrrrr** [comment]
first: no cams in public showers
image

second: new perma
image
image
image

**Comment by bearrrrrrrr** [comment]
first: no cams in public showers
image

second: new perma
image
image
image

**Comment by bearrrrrrrr** [comment]
first: no cams in public showers
image

second: new perma. layout of the showers/toilet via the hallway at the bottom right of the room is identical
image
image

**Comment by bearrrrrrrr** [comment]
and this is the full thing in strongdmb:
image

**Comment by Jamini** [comment]
Can you please confirm that there are no runtimes or adminlog spams due to missing a cryo controller if someone is in the pod before I approve this? That was an issue I had occur on port oscar.

**Review by Jamini — APPROVED** [review]
I'm being told the pod controller works. Ergo, approved.

**Comment by ShadzFen** [comment]
Merging due to time constraint but that PR should have been fixed to fit standard. Keep it in mind for the future

**Pull request merged**
