### PR TITLE
Ports multiple upstreams from Eris.

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

https://github.com/discordia-space/CEV-Eris/pull/5897
https://github.com/discordia-space/CEV-Eris/pull/5882
https://github.com/discordia-space/CEV-Eris/pull/5881
https://github.com/discordia-space/CEV-Eris/pull/5880

tl;dr adds trash ammo in maint for trash guns, as well as one-time-use kits that help you repackage/make ammo. fixes penetration, lets you dig out shrapnel and self-cauterize in big emergencies

## Why It's Good For The Game

We're changing scrap guns a bit. I think this + jamming would bring maint guns in line enough to allow them to have more consistent damage. If not, free mirror.

## Changelog
```changelog
add: scrap bullets/scrap bullet kits
```

### CODE REVIEW

**Review by Michiyamenotehifunana — APPROVED** [review]
Sneaky undocumented port of the money dupe fix, but everything looks about right!

**Comment by bearrrrrrrr** [comment]
wait what

**Review by Michiyamenotehifunana — DISMISSED** [review]
Now with immersive self-surgery! Still looking good.

**Comment by bearrrrrrrr** [comment]
IM NOT DONE YET TORI HOLON

**Comment by bearrrrrrrr** [comment]
ok im done :)

**Comment by Jamini** [comment]
> 
> 
> Sneaky undocumented port of the money dupe fix, but everything looks about right!

You mean the one we asked you to get in ages ago? 😼

**Comment by bearrrrrrrr** [comment]
Don't bully Tori :gun:

**Review by Jamini — COMMENTED** [review]
Huge File here. I'm not seeing anything super objectionable at a brief skim. Have you *tested* all this to confirm it all works as expected and doesn't break anything else bear?

**Comment by bearrrrrrrr** [comment]
> Huge File here. I'm not seeing anything super objectionable at a brief skim. Have you _tested_ all this to confirm it all works as expected and doesn't break anything else bear?

Yup. Tested, it all works. Double-tested upon asking, posted screenies in discord.

**Review by Jamini — APPROVED** [review]
Okay. 

**DENIED**

I mean _**Accepted.**_

**Pull request merged**
