### PR TITLE
hey who likes eris ports lol

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

porting porting porting
porting everyday
if i stop my porting,
my fingers willl melt away

## Why It's Good For The Game

https://github.com/discordia-space/CEV-Eris/pull/5982
https://github.com/discordia-space/CEV-Eris/pull/5995

## Changelog
```changelog
add: ported two minor features from Eris: roach gibber meat fix and new rituals for church
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
good to go, would do more but my gitkraken fucked itself and i won't be able to port more until i un-fuck it

**Comment by Jamini** [comment]
Nooooot a fan of merging the already very good priest stat-boost litanies into one litany. It feels like kinda blatant powercreep on the free stats that priests and acolytes get.

Gibber stuff is good.

Could these two ports be split up maybe?

**Comment by Michiyamenotehifunana** [comment]
I like the litany changes for less clutter, balance can be resolved by porting the cruciform energy changes later.

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks good.

**Pull request merged**
