### PR TITLE
Changes space bats into a nanoblob

### PR DESCRIPTION
**Pull request by Ikmachek**
## About The Pull Request
Space bats are stupid, know what's cooler? A nanohive that forms a blob and tries to eat players. None of this is modular due to just how much is changed and would be too MUCH to change.

## Why It's Good For The Game
As silly as a nanoblob with a UwU face is, it's better than bats, BUT IN SPACE!!!

## Changelog
```changelog
add: A cute new nanoblob!
```

### CODE REVIEW

**Review by Jamini — CHANGES_REQUESTED** [review]
Most of this looks decent. HOWEVER

Issue 1: 
please move 
code/modules/mob/living/simple_animal/hostile/nanoblob.dm
to
zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/nanoblob.dm
The file can remain unchanged. It just should be in the modular folder

Issue 2:
Please rename
icons/mob/nanoblob.dmi
to
zzzz_modular_occulus/icons/mob/nanoblob.dmi

Once this is done, change line 3 in nanoblob.dm to
icon = 'zzzz_modular_occulus/icons/mob/nanoblob.dmi'

Issue 3:
Please don't edit effects.dmi.
Just put your new effect into zzzz_modular/occulus/icon/mob/nanoblob.dmi

Then change line 48 in nanoblob.dm to 
con = 'zzzz_modular_occulus/icons/mob/nanoblob.dmi'

---

Once that stuff is changed, this can probably  be approved. Overall it looks good!

Could you also post an image of your blob so people can see it's adowoble face?

**Comment by drexample** [comment]
This is a TRAGEDY
How dare you

**Comment by Jamini** [comment]
> This is a TRAGEDY
> How dare you

"Rwesitance is fwutile." - Nanoblob, Dec 20 2420

**Review by Jamini — APPROVED** [review]

**Comment by Jamini** [comment]
Okay, now that the stuff that was requested to be modular is modular. This should be good.

I still  do want bats.dm to be restored, but it's low-priority

**Pull request merged**
