### PR TITLE
IC printer R&D Fix

### PR DESCRIPTION
**Pull request by Awesome4Real**
Allows IC printers to be fabricated through R&D again.

## About The Pull Request

Makes the IC Printer available through R&D like it's supposed to be. (Also this is my second PR ever and first here so let me know if I do anything wrong.)

## Why It's Good For The Game

The IC system is really fun and has been unavailable in-game for a bit.

## Changelog
```changelog
fix: Changed the research design to point towards the "IC Printer" instead of the "IC Printer Upgrade"
```

### CODE REVIEW

**Comment by Awesome4Real** [comment]
proof of functionality:
image

**Comment by Jamini** [comment]
The only reason I haven't fixed this is because we are on code freeze.

This also cannot be approved or merged, as we are on code freeze.

**Comment by Awesome4Real** [comment]
I getcha, I just wanted to try out making a PR to test if I was doing it right. Should I pull down the PR?

**Comment by Shadow-Quill** [comment]
> Should I pull down the PR?

Don't need to, all that the code freeze means is that other PRs won't get merged until the big rework PR

**Comment by Awesome4Real** [comment]
Thanks for letting me know Shadow! It should be fixed now.

**Review by Shadow-Quill — APPROVED** [review]

**Pull request merged**
