### PR TITLE
Convert maps to TGM & remove invalid pixel offsets

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Converts all dmm formatted maps to TGM format, and eradicates pixel_w and pixel_z from existence.

## Why It's Good For The Game

Fixes linting errors.

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
I scream internally.
Please hold.

**Review by Michiyamenotehifunana — APPROVED** [review]
I sure hope this works.

**Comment by Jamini** [comment]
Is this map format compatible with strongDMM?

**Comment by Shadow-Quill** [comment]
> Is this map format compatible with strongDMM?

For posterity, yes.

**Pull request merged**
