### PR TITLE
Disables reverse-pouring

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request
Have you ever mixed a drink, but then suddenly a chunk of your cocktail-in-progress suddenly flowed back into your soda can? Well fret not, for with this PR, all your upstream flow fears shall be eliminated! That's right, for the low, low price of your sanity and the merging of this PR, your greatest nightmares will be gone in a jiffy!

Spray bottles still reversepour.

## Why It's Good For The Game

Quality of life, a long standing issue, etc. etc.

## Changelog
```changelog Toriate
del: Removed reverse-pouring from everything but spraybottles.
```

### CODE REVIEW

**Review by ShadzFen — APPROVED** [review]
So it was a feature and not a bug after all. Amazing. Eris never ceases to amaze me. Non modular commenting, marked. All good.

**Comment by zackerycodestoo** [comment]
The name of the variable makes me think that it was intended to fill containers from a dispenser -- does getting water from a water cooler still work?

**Comment by ShadzFen** [comment]
Changes need to be made. As @zackerycodestoo pointed out, reverse pouring is needed specifically for the objects that dispense a fluid and can not be picked up. Maybe we could have a flag that can be attached to such items that allows them to reverse pour?

**Review by Jamini — APPROVED** [review]
Looks good. All Marked. unless anyone has anything else to add we should be good to go here.

**Pull request merged**
