### PR TITLE
Jamini admincleanup

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Major refactor of the Syzygy modular folder, merging it with the Occulus modular folder
Blacklisting for the MEK warhammer
depreciated NZR override removed

## Why It's Good For The Game

Housekeeping stuff

## Changelog
```changelog
admin: moved several files from the syzygy modular folder to occulus
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
rip funeee warhammer

**Comment by Jamini** [comment]
> rip funeee warhammer

It's still on the Mekhane disks. WHERE IT BELONGS

**Review by Michiyamenotehifunana — APPROVED** [review]
Good ol' spring cleaning.

**Comment by Jamini** [comment]
Conflict resolved by commiting both changes.

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks about right.

**Pull request merged**
