### PR TITLE
Church Nerf Part 1

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request

1) Most litanies have now gained nutrition costs, and the nutrition recovering litany now inflicts 3x as much toxin damage.
2) Cruciforms are now vulnerable to EMPs. Victims will have their cruciforms battery drained.
3) The Invigorate litany (priest upgrade only) will be able to restore EMP'd cruciforms.
4) The Mekhanite Seal is now a 6/6/4 oddity instead of a 12/12/8 one.

## Changelog
```changelog Toriate
balance: Cruciforms are now vulnerable to EMPs, and most litanies now cost nutrition.
```

### CODE REVIEW

**Comment by Jamini** [comment]
Emojicracy up for this before we merge it.

**Review by Jamini — APPROVED** [review]
Slightly less harsh nerfs as per discussion and emojicracy. This should be g2g now

**Review by Jamini — APPROVED** [review]
All the conflicts should be gone now right?

ALSO, while not pressing now. Slightly reducing the value of the Mekhanite seal (it exports for 4,800cr) might be something to think about in a future PR.

**Comment by bearrrrrrrr** [comment]
honestly not sure if the church needs nerfs with the new soulcrypt stuff. the buffs to crypts were pretty powerful.

**Comment by Jamini** [comment]
> honestly not sure if the church needs nerfs with the new soulcrypt stuff. the buffs to crypts were pretty powerful.
> 
> that, and the fact that a lot of the new stuff added to the bioreactor...doesn't seem to be seeing a lot of use. idk

Uh, the new longsword is redonk.
Printable medium pouches are also redonk. Especially as biomatter isn't that hard to get.
The oddities are insanely good, and evne if they were not, they are hilariously valuable to sell.
and nutrition is not hard at all to get for people in the church. Since their main jobs revolve around... making food.

Also note the crypts are similarly vulnerable to EMPs.

**Pull request merged**
