### PR TITLE
Catalyzer(catalyser?) Craftable Guns

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

Adds 4 new guns that have a unique yet familiar crafting system (Uses gun assembly-esque system) and are emaggable
Adds 2 Crafting items to create these new guns, One of them uniquely sprited while the other one uses an artwork oddity sprite.

CORSAIR: Shoots lethal rounds, requires manipulators.
ENFORCER: Shoots rubber rounds, Requires matter bins
SENTINEL: Shoots lasers, requires microlasers
DIDACT: Shoots plasma, requires capacitors.
image
(Image: Corsair topleft, Enforcer topright, didact bottom left, sentinel bottom right)

Experimental Stock: This is the end-craft item. Takes Core(see below) And Gunparts(5)

Catalyzer Cores: This is the start of the crafting process. Takes Stockparts to create a functioning core, That you then add to the stock to decide the guntype.

## KNOWN ISSUES:

> Single-handed sprites dont work. Trust me, i've tried doing it myself and with some help, But between eris' confuckling of sprites using both overlay AND itemstates, I cant get BOTH onehand and twohand sprites to work. I hate the fact i cant, But as these are 2hand focused guns, i'm sticking with twohand sprites over the onehand sprite.

Fixed by including parent parent code snippet.

> The 0 charge overlay does not work. This is most likely a flaw with how i did it, But as i currently have it it will stay at the low charge light instead of going empty. I dont know how to fix this.

Fixed by including more maths and checks.

## Why It's Good For The Game

Adds more guns that are fun and nice and honestly i dont actually know i spent like a week on the code, took a dip, then tortured myself spriting them and trying to finish. I really hate sprite + codework but my ambitions and dreams overcome my hatred.

## Changelog
```changelog
add: Enforcer Rubber-pellet Catalyzer gun
add: Corsair Shrapnel Catalyzer gun
add: Didact Plasma Catalyzer gun
add: Sentinel Laser Catalyzer gun
add: Crafting item "Inert Catalyst" and "Experimental Stock" with their associated crafting recipes in the "Guns" group.
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
Additionally pictures of the new guns would be appreciated, just for the sake of seeing what's getting added quickly and easily.

**Comment by Zenitheevee** [comment]
> 
> 
> Additionally pictures of the new guns would be appreciated, just for the sake of seeing what's getting added quickly and easily.

Fixed

**Comment by ShadzFen** [comment]
Perfect, thanks!

**Comment by Zenitheevee** [comment]
> 
> 
> Additionally pictures of the new guns would be appreciated, just for the sake of seeing what's getting added quickly and easily.

And image added with a guide on which is which.

**Review by ShadzFen — DISMISSED** [review]
All looks good! We'll have to see if the guns are properly balanced once in game, but the values look like they'll be fine. Quite excited to see some more craftable guns, especially the energy ones. Good job! Everything's modular, ready to go.

**Review by Jamini — APPROVED** [review]
Shadz forgot to actually approve it. Done.

**Pull request merged**
