### PR TITLE
eris ports but not bad this time

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

see above. just my last port batch w/o my disastrous fucking attempts at an erismed port...
also fixed an incorrectly labeled object causing something to be invisible...pog.

## Why It's Good For The Game

https://github.com/discordia-space/CEV-Eris/pull/6070
https://github.com/discordia-space/CEV-Eris/pull/5923
https://github.com/discordia-space/CEV-Eris/pull/5997
https://github.com/discordia-space/CEV-Eris/pull/6072
https://github.com/discordia-space/CEV-Eris/pull/5782

## Changelog
```changelog
add: admeme ticket system, pill/beakers
```

### CODE REVIEW

**Review by Jamini — DISMISSED** [review]
Thanks for the quick fix bear

**Comment by bearrrrrrrr** [comment]
small bugfix before i merge, hold plz

**Comment by bearrrrrrrr** [comment]
good to go

**Comment by bearrrrrrrr** [comment]
just going to add the slaught-o-matic PR while i'm here, actually...

**Review by Jamini — APPROVED** [review]
Looks good. I renamed the dumbfuckomatoc to the liberator after another disposable gun we wanted to get in the past.

**Pull request merged**
