### PR TITLE
Discord bot

### PR DESCRIPTION
**Pull request by vulppine**
See #360 for more details - this pull request is meant for the actual fixes to that PR

### CODE REVIEW

**Comment by vulppine** [comment]
so, i've left this alone for a little bit pending an issue related to restarts and Dream Daemon immediately crashing with the method i've implemented here

there's a couple solutions:
- integrate the functionality of the web server into the discord bot itself (considering how the likelihood of a website seems somewhat low
- have both the web server and the discord bot run constantly (which *might* have a low memory footprint, but i would have to test it and give the results back)

i'll defer to jamini on this one, since he's primarily the one with access to the server hardware

**Comment by vulppine** [comment]
i've went ahead and done the first choice - however, if the second choice is ever really needed, feel free to contact me and i'll help set it up!

**Comment by ShadzFen** [comment]
@Jamini this PR has been up for over a month and the author specified it's up to you to get it running apparently. Can we get this finished soon?

**Comment by Jamini** [comment]
When I actually get time to do it, yes. It has been a busy month for me.

I'm going to want Flipp there for getting this up and running in case we run into issues with the bot like last time.. I'd rather not merge it until we are ready.

**Review by Jamini — APPROVED** [review]
We are working on implementing this now.

**Pull request merged**
