### PR TITLE
Fixes captain voidsuit sprite

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Fixes the captain voidsuit sprite
Checks some files that didn't get checked before

## Why It's Good For The Game

<Simple bugfixs here

## Changelog
```changelog
fix: Captain voidsuit sprite now works properly
fix: Occultist files are now checked in the default DME
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
"Fixes captain voidsuit" is kinda vague... what was wrong with it?

**Comment by bearrrrrrrr** [comment]
> "Fixes captain voidsuit" is kinda vague... what was wrong with it?

the actual obj/ icon was displaying on a person when wearing it instead of the proper clothing sprite.
image

**Comment by Jamini** [comment]
> "Fixes captain voidsuit" is kinda vague... what was wrong with it?

*thousand tile stare*

**Review by ShadzFen — APPROVED** [review]
small modular fix. Extra DMEs are due to some issues with other PRs, keeping them avoids unchecking DM files.

**Pull request merged**
