### PR TITLE
Another Big Church Update, now starring: The Eye of the Protector

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request

The church will be getting a new thing!

eotp

Rather than hacking a vendor to get some whacky weapons and grenade disks, the church now has to work together and show people the church, gib roaches, and perform group litanies to unlock the disks!

This PR will port:
https://github.com/discordia-space/CEV-Eris/pull/5780
https://github.com/discordia-space/CEV-Eris/pull/5793
https://github.com/discordia-space/CEV-Eris/pull/5407
https://github.com/discordia-space/CEV-Eris/pull/5766

StrongDMM_d9L1OFGyKE

The bioprinter's disks has also been reorganized! The church will now start with 4 disks: The basic disk, a clothing disk, a basic weapon disk (shortsword and dagger only), and a church machine circuitboards disk. I also added a shortsword to the custodian's lockers.

StrongDMM_16xd1dOlVO

Church weapons have also been nerfed. All of their armor penetration values have been reduced in general, with the exception of the Scourge which seems to be an anti-personnel weapon to begin with. The halberd and shortsword have had some damage increase also. The Sword of Truth's sprites have also been fixed.

I have tried my best to fix all the wonky lore bits and typos. Also I just realized I completely forgot to look into nerfing the winebath, but goddamnit, it's gonna hafta be in another PR at this rate.

## Changelog
```changelog Toriate
add: Ported the Eye of the Protector from upstream
add: Bioprinter disks have been reorganized a bit!
```

### CODE REVIEW

**Comment by drexample** [comment]
wait before cruciforge gets put in

**Comment by ShadzFen** [comment]
Well we got DMM conflicts so it's not gonna get merged just yet. When is cruciforge planned for? I don't want this PR sitting here for days if it's something that can be added post-merge. @drexample

**Comment by Jamini** [comment]
The preacher has a copy of the church circuit boards disk in his locker.

**Comment by Michiyamenotehifunana** [comment]
Extraneous circuit boards disk now removed.

**Comment by Jamini** [comment]
Emojicracy passed. I'll lave it to @ShadzFen to approve it.

**Review by ShadzFen — APPROVED** [review]
All looks good. Some small modular overrides for upstream stuff added to work with out lore and code too. All looks good

**Pull request merged**
