### PR TITLE
Suggestions Box: Engineering Taperoll and Barracks Lightswitch Moving!

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request

Adds Engineering Tape to standard engineer's lockers, and moves the Aegis Barracks' lightswitch.
StrongDMM_JgWpEcCqTF

These two changes came from the suggestions box.

## Changelog
```changelog
add: Engineers now get engineering tape! A lightswitch has also been moved in the Aegis Barracks.
```

### CODE REVIEW

**Review by Jamini — DISMISSED** [review]
Looks good. Tak Tori

**Comment by ShadzFen** [comment]
Had to resolve a .DME conflict.

**Comment by Jamini** [comment]
@Michiyamenotehifunana  - This PR doesn't add any files. Can you grab the DME file from master and pop it into this branch to make sure we don't uncheck any files in the repo? Should only take a minute.

Once _CEV_Eris.dme is fixed, I'll just immediately merge it.

ALSO - You might want to keep a second lightswitch in the back. They are motion activated and only having one switch there means folks who aren't moving in the barracks will have the lights flick off on them.

**Comment by Michiyamenotehifunana** [comment]
Superseded by https://github.com/Occulus-Server/Occulus-Eris/pull/119

**Pull request closed without merging**
