### PR TITLE
Slight QoL adjustments to medical

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Edit: Also fixed the advanced scanner so it reads internal injuries properly.
Fixes access in some medbay doors so people are less likely to get trapped.
The medical stairwell now has generic NT access
Removed extranious door by the morgue that was keeping people from lower maints
Tweaked aft entrance to medbay maints slightly

image
image
image
image

Added missing floor tiles in medbay maints
Added missing firelocks off of areas with air alarms
Added some railings in medbay maints
Moved the tool rack by assistant spawn near cargo so it isn't blocking two spawns in
Removed the biomatter spawn from the roach kitchen
Replaced the iron doors in the roach kitchen with airlocks.
Edit: Adjusted morgue medbay area
Removed a fire alarm under glass on the bridge
Fixed up the cargo desk windoors a tiny bit

## Why It's Good For The Game

Minor maptweaks to make things a bit less obnoxious in medical maint and a few other areas

## Changelog
```changelog
fix: Advanced medical scanner once again reads breaks and infections.
map: Tweaked medical maint and medical a tiny bit
```

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
One thing Jamini, The door by the morgue at the bottom of the stairs is actually important. It prevents the entire medical lobby and primary hallway from being vented, if that window there gets destroyed. I put it there after a few complaints about that happening due to roachs.

**Review by fludd12 — DISMISSED** [review]
Everything looks good! One small note is that it looks like some areas were removed from certain tiles judging by the files changed view in git. That could totally be intentional, of course, but it's something to doublecheck before merging!

**Comment by fludd12** [comment]
(I'd get a more in-depth look but my git currently is a mess of uncommitted test changes that I'm slowly sorting out between work stuff)

**Comment by Jamini** [comment]
Double checked areas and fixed a few things
Mostly just adjusted areas.
Should be g2g

**Review by fludd12 — APPROVED** [review]
Looks good to me!

**Pull request merged**
