### PR TITLE
Vendor Prices/Nerfs Dr. Gibb

### PR DESCRIPTION
**Pull request by Ikmachek**
## About The Pull Request
On my way to fixing some odd vendor prices I noticed Dr. Gibb has all the flavors for insight cravings, not anymore!

## Why It's Good For The Game
Because skipping the club for 30 credits to sip from the galaxy's best soft drink isn't conductive to HRP

## Changelog
```tweak: Fixed some vendor prices
balance: Nerfed Dr. Gibb, he lost his medical degree
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
tbh if doctor gibb is a big dick thing it may be worth removing it from the vendors so it stays as a random maint loot drop for ez levels

it'd be neat imo, at least

**Comment by Jamini** [comment]
It's not a big-dick thing. Some dumbass over on Eris proper made a meme about "42" flavors and has Dr. Gibb giving all drink inspirations. I'm absolutely happy to see that gone.

**Comment by bearrrrrrrr** [comment]
That's what I'm saying. You could keep it as maint loot but entirely remove it from the soda vendors. It's why it costed 1k, after all >.>

**Comment by Jamini** [comment]
> That's what I'm saying. You could keep it as maint loot but entirely remove it from the soda vendors. It's why it costed 1k, after all >.>

It is used in a number of mixed drinks.

**Comment by bearrrrrrrr** [comment]
das fair nuff then

**Comment by ShadzFen** [comment]
Fixed up a merge conflict with your .DME file.

**Review by ShadzFen — APPROVED** [review]
All good, just some small modular changes. For future reference though, please make sure you use a new branch rather than your master branch. It gets a little tough to review if not uwu

**Pull request merged**
