### PR TITLE
Touch-ups to the Fight Club:tm:

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

The fight club had open plating underneath a doorway, catwalks underneath another, and had a manual valve under a wall. The last one isn't my fault, but this PR fixes all ol this!

~~We're also removing the fluid stain. I'm not budging from this.~~

Images: 
image

## Changelog
```changelog
add: Added more seating room, some more objects in general, to the fight club room.
del: Removes **Fluid** **Stain** from the fight club room.
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
removed the feature where the room instantly depressurized itself when you opened a door :)

**Review by Jamini — CHANGES_REQUESTED** [review]
Heathen, removing the white synthetic bloodstain. How could you.

Please re-add the curtain on the left window by the vaggie bedrooms. Then I can approve this.

**Comment by bearrrrrrrr** [comment]
Fixed! Unsure how I removed a curtain, didn't even touch that tile >.> all good now, though
image

**Review by zackerycodestoo — APPROVED** [review]
Requested changes addressed, approved

**Pull request merged**
