### PR TITLE
ports some oddities added to eris

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

ports https://github.com/discordia-space/CEV-Eris/pull/5732

## Why It's Good For The Game

More oddities good. Staying updated w/ upstream good.

## Changelog
```changelog
add: Added new oddities.
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
btw, checked these ingame, yes they all spawn properly and have proper sprites, don't worry

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks good, although there is no doubt that this file will need to be reorganized once we properly sync with upstream.

**Comment by bearrrrrrrr** [comment]
fixed an entire sentence not being in a description

fixed mentions to technomancer-whatever and now renames it to Cube stuff

**Review by ShadzFen — APPROVED** [review]
Upstream PR, non modular as usual. All good.

**Pull request merged**
