### PR TITLE
The absolutely awful Erismed2 Port

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
## About The Pull Request
This PR has been in the oven for over a month at this point, and it's full of kludgey bugfixes (actually only 1).

Most importantly, we get these PRs:
https://github.com/discordia-space/CEV-Eris/pull/5609
https://github.com/discordia-space/CEV-Eris/pull/5685
https://github.com/discordia-space/CEV-Eris/pull/5737

We will get Rimworld-style internal organs with efficiency ratings, and a spiffier surgery UI than ever before. 

## KNOWN ISSUES
Currently, everyone spawns with 3 eyes. No, not 3 eyeballs, 3 pairs of eyeballs. One spawns in nullspace and will be GC'd within the first minute of spawning in, yet still shows up in the surgery UI until it's autodeleted. The other two are literal duplicates of each other and only one should show up in the surgery UI.

This causes a weird thing where your eye health will cycle between the two sets of eyes for the first minute after you spawn in. You can blind yourself entirely in one set, while the other set can still see perfectly, causing your vision to flash in and out until the nullspace eye gets deleted and your true pair of eyes come out on top.

As far as I can tell, line 1136 in `code\modules\mob\living\carbon\human\human.dm` is the culprit, but I am absolutely stumped.

## TESTING STATUS
I have confirmed that starting the server and spawning in will not cause runtimes. Nerves and such function as expected. Surgery UI works as intended. Hands and feet get nerves and muscles as well, however they do not affect what arms and legs do (dealing with this should be in another PR for the sake of our collective sanity).

THIS WILL REQUIRE FULL SCALE TESTING IN SOME FORM BEFORE WE FULLY COMMIT. I can't test every aspect of the new organs on my own.

## Changelog
```changelog Toriate
add: Ported Erismed2 from upstream
```

### CODE REVIEW

**Comment by ShadzFen** [comment]
CI Failure: 

warning: field access requires static type: "dislocated"
code/modules/mob/living/carbon/human/human_organs.dm:9:50: add a type annotation after /list here

**Comment by Michiyamenotehifunana** [comment]
> CI Failure:
 
Resolved.

**Comment by ShadzFen** [comment]
Thanks. I don't think I'm gonna be able to review this tonight though. You'll have to wait until tomorrow unless Jams wants to review it.

**Comment by Michiyamenotehifunana** [comment]
Reviewing this would be pure CBT tbh, so no rush

**Review by ShadzFen — APPROVED** [review]
Well that took 2 hours. All looks good. Good job!

**Pull request merged**
