### PR TITLE
Hypospray mKII

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request

Ports over Hypospray MKIIs.
Replaces CMO locker with Occulus custom version (to include hypospray, and maintain modular-ability)
Replaces Medical vendor with occulus version in medbay(to include hypospray kits, and maintain modular-ability)
Syringes are currently faster to inject with then generic hyposprays MKIIs. Generic hypos have more capacity.
Hypo's take a while to inject into suits, due to method. Syringes better for suit injections.
Combat variant of Hypospray has nanite drugs, and stimulants. May need to tune this back a bit, pending pvp feedback. Hard to get a good read on whats useful without, though it is incredibly rare to have without being an antag.
May need to reduce CMO hypo starting drugs as well, depending. Feedback on this appreciated.
Edit:
The CMO's hypospray MKII, has faster injection time then the generic ones, better then syringes, and has a capacity of 120u.
The combat hypospray MKII has an instant injection, 60 u capacity, and bypasses suit wait time.
Hypospray MKII's can be emagged to make them inject at instantly at combat levels.
Hypospray vials in hypokits start with 30u of a medicine, but have the capacity for 60.
CMO's hypokit starts with several differants vials of basic medicine loaded at 60u.
Combat hypokit starts with 2 vials+1 loaded of combat drugs: Synaptizine, hyperzine, oxycodone, trauma_control_system, and Nanosymbiotes, each mixed together for a total of 50u per vial
This is availible for purchase at traitor uplinks for 15 TC, though like other traitor gear, it can be found extremely rarely.
CMO Hypospray MKII replaced Hypospray in Traitor contract theft objective.

## Why It's Good For The Game
Gives medical something nice and new to play with. Handy tool for medical.
Provides some variety and choice besides pill vs syringe.

## Changelog
```changelog
add: Generic Hypospray MKII- For all use. 60u vials. Slower then syringe on use. Can swap out vials, for convienance.
add: CMO Hypospray MKII 'deluxe'. Faster usage, more capacity. 120u vials.
add: Combat hypospray MKII. Found only in combathypokits. Rarity set to 100. Basically traitor gear. Acts instantly. Bypasses normal suit wait. 60u vials. Can reload combatstyle-like magazines.
add:Combat hypokit to traitor uplink, 15 TC. 3 vials 50u of combat drugs.
add: Hypospray kits. Medkit like packs with 1 hypospray and 2 hypovials for use. Variety of treatment packs.
tweak: Swapped out Medical Vendor for occulus varient (contains hypospray kits)
tweak: Swapped out CMO closet for occulus variant (contains CMO hypospray kit)
tweak: updates filepath in traitor contracts for new hypo.

soundadd:  3 new hypospray sounds
imageadd: hypospray sprites, 
imageadd: hypovial sprites
imageadd: hypospray kit sprites

```

### CODE REVIEW

**Comment by ShadzFen** [comment]
`Syringes are currently faster to inject with then generic hyposprays MKIIs. Generic hypos have more capacity.`
`Hypo's take a while to inject into suits, due to method. Syringes better for suit injections.`

Why are we nerfing hyposprays? The whole point of the hypospray is for it to be a hard to find better injection item than syringes overall...

`May need to reduce CMO hypo starting drugs as well, depending. Feedback on this appreciated.`

Why? How much does it start with? Don't skimp on the info in a PR, I'd rather be flooded with info than lack info.

Can we also get some pictures of the new sprites? Do they show up when held?

**Comment by Jamini** [comment]
Adding Do No Merge, as we are on codefreeze.

**Comment by RadiantFlash7** [comment]
> `Syringes are currently faster to inject with then generic hyposprays MKIIs. Generic hypos have more capacity.`
> `Hypo's take a while to inject into suits, due to method. Syringes better for suit injections.`
> 
> Why are we nerfing hyposprays? The whole point of the hypospray is for it to be a hard to find better injection item than syringes overall...
> 
The new version of hyposprays, are for public use among all medical. I'm not adding the newer hyposprays MKIIs to medical, with a better injection time then syringes. Because then no one will use syringes. The current version of hyposprays MKIIs can swap out medicine vials super quickly, and have more capacity. They take slightly longer to use then the normal syringe in general, as a trade off for convienance. 
> `May need to reduce CMO hypo starting drugs as well, depending. Feedback on this appreciated.`
> 
> Why? How much does it start with? Don't skimp on the info in a PR, I'd rather be flooded with info than lack info.
> 
The CMO's hypospray MKII, has faster injection time then the generic ones, better then syringes, and has a capacity of 120u.
The combat hypospray MKII has an instant injection.
Hypospray MKII's can be emagged to make them inject at instantly at combat levels.
Hypospray vials in hypokits start with 30u of a medicine, but have the capacity for 60.
CMO's hypokit starts with several differants vials of basic medicine loaded at 60u. 
Combat hypokit starts with 2 vials+1 loaded of combat drugs: Synaptizine, hyperzine, oxycodone, and Nanosymbiotes, at 60u.
This is availible for purchase at traitor uplinks for 15 TC, though like other traitor gear, it can be found extremely rarely.


The thing that I'm concerned about, is the CMO's starting hypo vial has nanite drugs in it. 20 units of oxy rush, 20 units of Trauma control, and 20 units of nanosymbiotes. This is intended to provide the CMO a starting round buff and to give them a bit of uniqueness. Given how frequently people are hurt on Eris code, I expect this would get used up pretty quickly. It's got 6 uses worth of injections at 10u. 4 at 15u. If it's too much of a buff, I can always swap it out to 60u of tricord.

> Can we also get some pictures of the new sprites? Do they show up when held?
This is the inhand icons for the kits and hypospray MKII
inhandicons
This is the new hypokit icons. Basically minimedkits.
hypokit icons
This is the new hypospray icons.
hypoicons
These are the new hypovial icons. Note: Hypovials use mutable code like beakers, and are filled with reagents, hence why it's see through in the middle. Reagents change color inside based on what reagents are in it. 
hypovialicons

**Comment by ShadzFen** [comment]
Alright, that's all really good info (that should have been part of the initial PR), thanks! 

Just one thing, the brute kit is pink, while the radiation kit is red. This goes against pretty much every other colour code in medical. Is there any way you could change the `brute_mini` to be the red kit, and then `rad_mini` to either be the pink kit **or preferably** have a colour more similar to radiation treatment stuff. (The Russians tend to colour most of their radiation medical kits orange, and most other countries tend to follow a similar colour code for it. Maybe it could be a dark orange to distinguish it from the yellow burn kit?)

**Comment by RadiantFlash7** [comment]
> Alright, that's all really good info (that should have been part of the initial PR), thanks!
Yeah, Sorry. Side effect of coding/playtesting for 10 hours, and making the PR at 2 am >..>;;;

> 
> Just one thing, the brute kit is pink, while the radiation kit is red. This goes against pretty much every other colour code in medical. Is there any way you could change the `brute_mini` to be the red kit, and then `rad_mini` to either be the pink kit **or preferably** have a colour more similar to radiation treatment stuff. (The Russians tend to colour most of their radiation medical kits orange, and most other countries tend to follow a similar colour code for it. Maybe it could be a dark orange to distinguish it from the yellow burn kit?)
I can swap these out, no big deal!

**Comment by RadiantFlash7** [comment]
Sprites changed, code cleaned up, travis passed!
brutemob
bruteicon

**Comment by Michiyamenotehifunana** [comment]
How does this work with the `steal a hypospray` traitor contract?

**Comment by RadiantFlash7** [comment]
> How does this work with the `steal a hypospray` traitor contract?

...I wish I was smart enough to have an answer to that. Currently it doesn't. I'll have to dig into the contracts and see if I can disable the existing hypo contract and add one for the new hypospray.

**Comment by RadiantFlash7** [comment]
Combat hypo no longer straight upgrade to CMO hypospray. 
CMO hypo now only hypo to use large Hypo vials.
traitor hypospray contract adjusted to use new hypo (PR No longer modular)
Descriptions adjusted to reflect possible reasoning to steal CMO hypospray.
Adjusted code to check if hypospray penetrates suits when injecting for combat hypo.

Should be good now, I think.

**Comment by Torque4607** [comment]
I am 100% in support of new hypospray mechanics/changes. This appears to be a huge improvement over how hyposprays are currently handled by Eris, both codewise and 'this is much nicer'-wise.

**Review by Jamini — APPROVED** [review]
All Modular and marked.

I've seen these in action on other servers. They are really quite great.. possibly too great but that will need to be seen.

**Comment by RadiantFlash7** [comment]
> All Modular and marked.
> 
> I've seen these in action on other servers. They are really quite great.. possibly too great but that will need to be seen.

Hopefully with the hypos being slower then syringes, it'll not be too great. Remains to be scene.

**Review by Jamini — APPROVED** [review]
Bad cat! Time for your punishment! *brandishes Whip!*

**Pull request merged**
