### PR TITLE
Adds a new gun, the DS 'Glasgow'

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

Adds a new gun, the DSS PDW 'Glasgow', a heavier, more rugged version of the Martin that chews through batteries. You can find screenshots in coding-discussion.

## Why It's Good For The Game

Gun.

image

## Changelog
```changelog
add: New gun, the DSS PDW 'Glasglow'
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
To be noted, this isn't in any maint loot or anything yet, so, technically WIP

**Comment by bearrrrrrrr** [comment]
image
pic of individual components

**Comment by bearrrrrrrr** [comment]
nvm i've been told it's already in the loottable

pr complete
Later, nerdssss

**Comment by ShadzFen** [comment]
I would appreciate more info regarding the weapon. What fire modes does it have? What is the difference between the 3 types of gun that there appear to be? The standard, the lethal, the blue one? Some pics of it in all 4 directions while held would be cool too. What's the fire rate? How many shots can you get out of a 200 cell battery for example? Does it use small cell batteries?

**Comment by bearrrrrrrr** [comment]
You can find all of that information in the code, but;
the red and blue sprites are for when it is in lethal and shock mode respectively

it uses what is basically a lighter version of the Martin's inhand with a blue tip
It can fire two shots from a 200 cell, due to the fact it takes up a large amount of battery per shot. Its damage multiplier is 1.4. It is a medium sized item, compared to the Martin's small.

**Comment by bearrrrrrrr** [comment]
https://cdn.discordapp.com/attachments/777382113737572393/791445802832101436/2020-12-23_18-19-45.mp4

shows firemodes, sprites, etc

**Review by ShadzFen — APPROVED** [review]
All looking good from here. Heavy revolver style laser pistol

**Pull request merged**
