### PR TITLE
SUS AMOGUS PORTS!!!! IMPOSTER!!!!

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

AMONGUS!!!!!

## Changelog
```changelog
add: fire slug buff
fix:, eotp runtime fix
add: ablative vest now covers the  full body w/ the exception of hands and feet
add:aegis crates now actually contain aegis guns and armor, lowered surplus crate price
add:sword of truth now does more damage during a crusade
```

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
undid 5893 since that shit don't WORK-

**Comment by Jamini** [comment]
Bear, you gotta follow the template a bit better. Even for ports. >.>

**Comment by bearrrrrrrr** [comment]
> Bear, you gotta follow the template a bit better. Even for ports. >.>

SUS!!!!!!

IMPOSTER!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ALERT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Jamini** [comment]
> > Bear, you gotta follow the template a bit better. Even for ports. >.>
> 
> SUS!!!!!!
> 
> IMPOSTER!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ALERT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

No seriously, especially the changelog. It goes into places we can't see commits. We need details in your PR body

**Comment by bearrrrrrrr** [comment]
FIXED!! AMOGUS

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks good, nothing peculiar in here.

**Pull request merged**
