### PR TITLE
Two minor lore fixes and makes the bomber jacket have some armor

### PR DESCRIPTION
**Pull request by Ikmachek**
## About The Pull Request
Three things, fixes the tax app to not be from the future, Jams missed ONE NEV mention, and the bomber jacket now has minor armor.

## Why It's Good For The Game
"but Ikky, this should be atomized" you whine at me.

"Skill issue", I chadly reply back, telling you these minor lore edits are good for the game and so is making an item inline with others.

You can't help but approve this PR and beg for forgiveness for being wrong.

```changelog
tweak: Two lore fixes, and gives bomber jacket minor armor
```

### CODE REVIEW

**Review by Jamini — APPROVED** [review]
PR denied and closed.

**Comment by Jamini** [comment]
Suffer, nerd.

**Comment by Ikmachek** [comment]
I FORGOT TO COMPILE AND TEST, MY HUBRIS

**Comment by RadiantFlash7** [comment]
> I FORGOT TO COMPILE AND TEST, MY HUBRIS

Like you said. Skill issue. ;P

**Pull request merged**
